import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, MotionConfig, motion, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Plus, Upload, Download, Share2, GitBranch, Layers3, ScanLine, BookOpen, SlidersHorizontal, Play, Pause, RotateCcw, X, Check, Search, ShieldQuestion, Command as CommandIcon, LocateFixed, ChevronDown, AlertTriangle, Trash2, Braces, Orbit, ExternalLink, Maximize2, Minimize2 } from 'lucide-react';
import { compileQuestion, compileWorld, createBranch, definitionForWorld, definitions, interpretCommand, parseWorld, simulate, switchBranch, updateWorld } from './core';
import type { CompileResult, Metric, SimulationResult, WorldDefinition, WorldDocument, WorldKind } from './core/types';
import { deleteWorld, exportWorld, listWorlds, readShare, saveWorld, shareUrl } from './storage';
import { Modal } from './components/Modal';

const WorldScene=lazy(()=>import('./components/WorldScene'));
const sceneFallback=<div className="scene-loading"><Orbit/><span>Opening spatial view</span></div>;
type Panel='parameters'|'evidence'|'model'|'why'|'challenge';
const tabs:{id:Panel;label:string;icon:typeof BookOpen}[]=[{id:'parameters',label:'Controls',icon:SlidersHorizontal},{id:'evidence',label:'Source DNA',icon:BookOpen},{id:'model',label:'X-ray',icon:ScanLine},{id:'why',label:'Why?',icon:Search},{id:'challenge',label:'Challenge',icon:ShieldQuestion}];
const format=(n:number)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:2}):'—';

export function App(){
  const [world,setWorld]=useState<WorldDocument|null>(null);
  const [screen,setScreen]=useState<'home'|'library'|'world'>('home');
  const [compiled,setCompiled]=useState<CompileResult|null>(null);
  const [researching,setResearching]=useState('');
  const [about,setAbout]=useState(false);
  const [notice,setNotice]=useState('');
  const [saveStatus,setSaveStatus]=useState('');
  const [saved,setSaved]=useState(()=>listWorlds());
  const [demo,setDemo]=useState(false);
  const file=useRef<HTMLInputElement>(null);
  const reduced=useReducedMotion()??false;
  const notify=useCallback((text:string)=>setNotice(text),[]);
  const open=useCallback((next:WorldDocument)=>{setWorld(next);setScreen('world');setCompiled(null);},[]);
  useEffect(()=>{
    const navigate=()=>{
      const hash=location.hash;
      try{
        if(hash.startsWith('#/share/')){open(readShare(hash.slice(8)));return;}
        if(hash.startsWith('#/explore/')){const kind=hash.slice(10) as WorldKind;const def=definitions.find(d=>d.id===kind);if(def){open(compileWorld(def.question,kind).world);return;}}
        if(hash.startsWith('#/world/')){const match=listWorlds().find(s=>s.world.id===hash.slice(8));if(match){open(match.world);return;}notify('That world is not saved on this device. Open a shared link or import its file.');}
        setScreen(hash==='#/library'?'library':'home');setCompiled(null);setDemo(false);
      }catch{setScreen('home');notify('This world could not be opened. Its link is incomplete or its data failed validation.');}
    };
    navigate();window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate);
  },[notify,open]);
  useEffect(()=>{if(!world)return;const result=saveWorld(world);setSaveStatus(result.message);if(result.ok)setSaved(listWorlds());},[world]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(id);},[notice]);
  useEffect(()=>{const listener=()=>setSaved(listWorlds());window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener);},[]);
  async function create(question:string,kind?:WorldKind){try{setDemo(false);setResearching(question);setCompiled(await compileQuestion(question,kind));}catch(err){notify(err instanceof Error?err.message:'The question could not be compiled.');}finally{setResearching('');}}
  function enter(next:WorldDocument){const result=saveWorld(next);setSaveStatus(result.message);open(next);history.pushState(null,'','#/world/'+next.id);}
  async function importFile(f:File|undefined){if(!f)return;try{if(f.size>1_000_000)throw new Error('World files must be under 1 MB.');const next=parseWorld(await f.text());enter({...next,id:crypto.randomUUID(),updatedAt:new Date().toISOString()});notify('World imported and validated.');}catch(err){notify(err instanceof Error?err.message:'Invalid world file.');}finally{if(file.current)file.current.value='';}}
  async function share(){if(!world)return;try{const url=shareUrl(world);await navigator.clipboard.writeText(url);notify('Share link copied. It contains this world’s current state.');}catch(err){notify(err instanceof Error?err.message:'Could not copy the link. Export your world instead.');}}
  return <MotionConfig reducedMotion="user"><a href="#main" className="skip-link">Skip to experience</a><header className="site-header"><a className="wordmark" href="#/" aria-label="Elsewhere home"><span className="brand-symbol" aria-hidden="true"/>Elsewhere<span className="brand-dot">.</span></a><nav aria-label="Main navigation"><a className={screen==='library'?'active':''} href="#/library">World library <span className="nav-count">{definitions.length.toString().padStart(2,'0')}</span></a><button onClick={()=>setAbout(true)}>About <ArrowUpRight size={14}/></button></nav><div className="header-status"><span className="status-dot"/>LOCAL COMPUTE<span className="header-divider"/>NO API REQUIRED</div></header>
    <main id="main" tabIndex={-1}>
    {screen==='home'&&!compiled&&!researching&&<Home onCreate={create} onDemo={()=>{const next=compileWorld('Suppose Manhattan had no private cars.','manhattan');enter(next.world);setDemo(true);}} reduced={reduced}/>}
    {screen==='library'&&!compiled&&!researching&&<section className="library-page page-wrap"><div className="library-heading"><div><p className="eyebrow">THE ATLAS / {definitions.length} COMPILED WORLDS</p><h1>A place for your curiosity.</h1><p>Open a world. Follow a connection. Change an assumption.</p></div><button className="secondary" onClick={()=>file.current?.click()}><Upload size={16}/>Import world</button></div><div className="world-list">{definitions.map((d,i)=><button className="world-row" key={d.id} onClick={()=>create(d.question,d.id)}><span className="row-number">0{i+1}</span><div className={'world-thumb thumb-'+d.id}><WorldGlyph kind={d.id}/></div><div className="world-row-copy"><span className="eyebrow">{d.category}</span><h2>{d.title}</h2><p>{d.description}</p></div><ArrowUpRight className="row-arrow"/></button>)}</div><div className="section-heading saved-heading"><div><p className="eyebrow">YOUR EXPLORATIONS</p><h2>Saved on this device <span className="muted">/ {saved.length}</span></h2></div></div>{saved.length===0?<div className="empty-state"><GitBranch/><p>Your first world is waiting.</p><span>Worlds and branches save automatically as you explore.</span></div>:<div className="saved-list">{saved.map(({world:w,recovered})=><div className="saved-row" key={w.id}><button onClick={()=>enter(w)}><span><strong>{w.title}</strong><small>{w.branches.length} realities · {new Date(w.updatedAt).toLocaleDateString()}{recovered?' · Recovered snapshot':''}</small></span><ArrowUpRight size={18}/></button><button className="icon-button" aria-label={'Delete '+w.title} onClick={()=>{try{deleteWorld(w.id);setSaved(listWorlds());notify('Saved world removed from this device.');}catch{notify('Device storage is unavailable.');}}}><Trash2 size={16}/></button></div>)}</div>}</section>}
    {researching&&<Researching question={researching}/>}
    {compiled&&<Compilation result={compiled} reduced={reduced} onEnter={()=>enter(compiled.world)} onCancel={()=>setCompiled(null)}/>}
    {screen==='world'&&world&&!compiled&&!researching&&<WorldExplorer key={world.id} world={world} setWorld={setWorld} reduced={reduced} notify={notify} saveStatus={saveStatus} onShare={share} demo={demo} onStopDemo={()=>setDemo(false)}/>}
    </main>
    {screen!=='world'&&!compiled&&!researching&&<footer className="site-footer"><span>AN INSTRUMENT FOR UNDERSTANDING</span><span>Built by <button onClick={()=>setAbout(true)}>Shriyan Avadhanula <ArrowUpRight size={12}/></button></span><span>EXPLORE WHAT IS. CHANGE WHAT COULD BE.</span></footer>}
    <input ref={file} className="sr-only" type="file" accept=".elsewhere,application/json" aria-label="Import .elsewhere file" onChange={e=>void importFile(e.target.files?.[0])}/>
    <AnimatePresence>{notice&&<motion.div className="toast" role="status" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0}}><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={16}/></button></motion.div>}</AnimatePresence>
    {about&&<Modal title="ABOUT ELSEWHERE" onClose={()=>setAbout(false)}><div className="about-content"><p className="eyebrow">A QUESTION SHOULD SOMETIMES BECOME A WORLD.</p><h1>Understanding is<br/>a place you can go.</h1><p>Some ideas are too connected to fit inside a paragraph. Elsewhere gives those ideas space: a world you can enter, change, and question.</p><div className="about-principles"><div><Braces/><h3>Executable ideas.</h3><p>Structured worlds, deterministic simulations, and branches you can reopen.</p></div><div><BookOpen/><h3>Visible assumptions.</h3><p>Inspect the equations, context, limitations, and evidence behind a result.</p></div></div><div className="creator"><img src={import.meta.env.BASE_URL+'creator.jpg'} width="100" height="120" alt="Shriyan Avadhanula"/><div><span className="eyebrow">CREATED BY</span><h2>Shriyan Avadhanula</h2><p>Building software that makes complex systems easier to explore.</p><a href="https://github.com/SriBYJU/Elsewhere" target="_blank" rel="noreferrer">Explore the source <ArrowUpRight size={15}/></a></div></div><p className="fine-print">An independent, open-source project. Authored and generated worlds expose assumptions and limitations; the neural network performs actual local training. No paid inference, account, or subscription is required.</p></div></Modal>}
  </MotionConfig>;
}

function Researching({question}:{question:string}){
  const steps=['Interpret the question','Retrieve public context','Map entities and connections','Build the simulation','Open the interactive world'];
  return <section className="compilation page-wrap researching" aria-live="polite"><div className="compile-layout"><div><p className="eyebrow">QUESTION → RESEARCH → MODEL → SIMULATION → WORLD</p><h1>Building a place<br/>you can <span className="accent">enter.</span></h1><p className="compile-question">{question}</p><p className="fine-print">Elsewhere is collecting bounded public context and constructing a transparent local model. If research is unavailable, compilation continues offline and records that limitation.</p></div><div className="compile-process"><div className="compile-graph" aria-hidden="true"><WorldGlyph kind="system"/><div className="compile-orbit"/></div><ol>{steps.map((step,index)=><motion.li key={step} initial={{opacity:.25,x:8}} animate={{opacity:[.3,1,.3],x:0}} transition={{duration:1.7,delay:index*.18,repeat:Infinity}}><span>{(index+1).toString().padStart(2,'0')}</span><div><strong>{step}</strong><small>{index===1?'Public context only; causal assumptions stay separate.':'Preparing an inspectable, deterministic stage.'}</small></div></motion.li>)}</ol><div className="compile-route"><span className="status-dot"/>COMPILING WORLD<span>BOUNDED RESEARCH / $0 INFERENCE</span></div></div></div></section>;
}

function Home({onCreate,onDemo,reduced}:{onCreate:(q:string,k?:WorldKind)=>void;onDemo:()=>void;reduced:boolean}){
  const [question,setQuestion]=useState('');
  return <><section className="hero"><div className="hero-scene" aria-hidden="true"><Suspense fallback={null}><WorldScene kind="manhattan" reducedMotion={reduced} decorative/></Suspense></div><div className="hero-vignette"/><div className="hero-content"><div className="eyebrow hero-eyebrow"><span className="tiny-cross">+</span> REALITY, OPEN TO QUESTION</div><h1>Turn questions<br/>into <span>worlds.</span></h1><p className="hero-description">Some answers deserve more than words.<br/>Enter them. Change them. Understand them.</p><form className="question-form" onSubmit={e=>{e.preventDefault();onCreate(question);}}><label htmlFor="world-question" className="sr-only">What do you want to understand?</label><CommandIcon size={19}/><input id="world-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} placeholder="What do you want to understand?" required/><button type="submit" aria-label="Compile world"><ArrowRight size={21}/></button></form><div className="hero-try"><span>TRY A QUESTION</span><button onClick={()=>onCreate('Suppose Manhattan had no private cars.','manhattan')}>What if Manhattan had no cars? <ArrowUpRight size={13}/></button></div><div className="hero-actions"><button className="text-action" onClick={onDemo}><Play size={13} fill="currentColor"/>Watch a living demo <span>~45 SEC</span></button></div></div><div className="hero-coordinates"><span>40°46′ N &nbsp; 73°58′ W</span><strong>MANHATTAN / AN ALTERNATE POSSIBILITY</strong><span>SCHEMATIC GEOMETRY · ILLUSTRATIVE SCENARIO</span></div><div className="hero-bottom"><span><span className="status-dot"/>ANY SYSTEM. COUNTLESS POSSIBILITIES.</span><a href="#/library">Find your elsewhere <ArrowRight size={16}/></a></div></section><section className="discover-strip"><p className="eyebrow">CHOOSE A WAY IN</p><div>{definitions.map((d,i)=><button key={d.id} onClick={()=>onCreate(d.question,d.id)}><span className="discovery-no">0{i+1}</span><span><small>{d.category}</small><strong>{d.title}</strong></span><ArrowUpRight size={18}/></button>)}</div></section></>;
}

function WorldGlyph({kind}:{kind:WorldKind}){return <svg viewBox="0 0 150 90" fill="none" aria-hidden="true">{kind==='manhattan'?Array.from({length:12},(_,i)=><path key={i} d={`M${20+i*9} ${65-i%3*9}v-${15+i%4*8}l8-4v${15+i%4*8}z`} fill={i%3===0?'#8ca796':'#354d48'} stroke="#8ca796" strokeWidth=".5"/>):<>{[0,1,2].flatMap(layer=>[0,1,2].flatMap(n=>[0,1,2].map(m=><path key={`${layer}${n}${m}`} d={`M${20+layer*38} ${18+n*25}L${58+layer*38} ${18+m*25}`} stroke="#466771"/>)))}{[0,1,2,3].flatMap(layer=>[0,1,2].map(n=><circle key={`${layer}${n}`} cx={20+layer*38} cy={18+n*25} r="4" fill={layer===3?'#d1ec9c':'#85ccdb'}/>))}</>}</svg>;}

function Compilation({result,reduced,onEnter,onCancel}:{result:CompileResult;reduced:boolean;onEnter:()=>void;onCancel:()=>void}){
  const [visible,setVisible]=useState(reduced?result.stages.length:1);
  useEffect(()=>{if(reduced)return;const timer=setInterval(()=>setVisible(v=>Math.min(v+1,result.stages.length)),210);return()=>clearInterval(timer);},[reduced,result.stages.length]);
  return <section className="compilation page-wrap"><button className="text-action" onClick={onCancel}><ArrowLeft size={15}/>Back</button><div className="compile-layout"><div><p className="eyebrow">THE REALITY COMPILER</p><h1>A question.<br/>A system.<br/><span className="accent">A world.</span></h1><p className="compile-question">{result.world.question}</p><p className="fine-print">{result.world.kind==='system'?'Compiled from a bounded public-context pass and a disclosed system archetype. Causal links remain visible modeling assumptions.':'Compiled locally from an authored model. This record exposes its evidence and constraints.'}</p><button className="primary" onClick={onEnter}>Enter Elsewhere <ArrowRight size={18}/></button></div><div className="compile-process"><div className="compile-graph" aria-hidden="true"><WorldGlyph kind={result.world.kind}/><div className="compile-orbit"/></div><ol>{result.stages.slice(0,visible).map((s,i)=><motion.li key={s.name} initial={{opacity:0,x:reduced?0:12}} animate={{opacity:1,x:0}}><span>{(i+1).toString().padStart(2,'0')}</span><div><strong>{s.name}</strong><small>{s.detail}</small></div><Check size={15}/></motion.li>)}</ol><div className="compile-route"><span className="status-dot"/>{visible===result.stages.length?'REALITY READY':'REVEALING WORLD STRUCTURE'}<span>{result.route.toUpperCase()} / $0 INFERENCE</span></div></div></div>{result.notices.map(n=><p className="compile-note" key={n}><BookOpen size={14}/>{n}</p>)}</section>;
}

function WorldExplorer({world,setWorld,reduced,notify,saveStatus,onShare,demo,onStopDemo}:{world:WorldDocument;setWorld:React.Dispatch<React.SetStateAction<WorldDocument|null>>;reduced:boolean;notify:(s:string)=>void;saveStatus:string;onShare:()=>void;demo:boolean;onStopDemo:()=>void}){
  const definition=definitionForWorld(world);
  const result=useMemo(()=>simulate(world.kind,world.parameters,world.time,world.blueprint),[world.kind,world.parameters,world.time,world.blueprint]);
  const baseline=world.branches.find(b=>b.id==='baseline')??world.branches[0];
  const baselineResult=useMemo(()=>simulate(world.kind,baseline.parameters,baseline.time,world.blueprint),[world.kind,baseline.parameters,baseline.time,world.blueprint]);
  const [panel,setPanel]=useState<Panel>('parameters');
  const [immersive,setImmersive]=useState(false);
  useEffect(()=>{
    if(!immersive)return;
    const previous=document.body.style.overflow;
    document.body.style.overflow='hidden';
    const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!document.pointerLockElement)setImmersive(false);};
    window.addEventListener('keydown',escape);
    return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',escape);};
  },[immersive]);
  const [compare,setCompare]=useState(false);
  const [selected,setSelected]=useState('');
  const [focus,setFocus]=useState('');
  const [command,setCommand]=useState('');
  const [playing,setPlaying]=useState(false);
  const [dataView,setDataView]=useState(false);
  const [branchDialog,setBranchDialog]=useState(false);
  const [branchName,setBranchName]=useState('');
  const [demoStep,setDemoStep]=useState(0);
  const [pinned,setPinned]=useState<string[]>([]);
  const currentMetric=result.metrics.find(m=>m.id===selected)??result.metrics[0];
  const active=world.branches.find(b=>b.id===world.activeBranchId);
  function mutate(values?:Record<string,number>,time?:number){setWorld(w=>w?updateWorld(w,values,time):w);}
  useEffect(()=>{
    if(!playing)return;
    const id=setInterval(()=>{if(document.hidden)return;setWorld(w=>{if(!w)return w;return updateWorld(w,undefined,Math.min(definition.time.max,w.time+definition.time.step));});},world.kind==='neural'?170:500);
    return()=>clearInterval(id);
  },[playing,definition.time.max,definition.time.step,setWorld,world.kind]);
  useEffect(()=>{if(world.time>=definition.time.max)setPlaying(false);},[world.time,definition.time.max]);
  useEffect(()=>{
    if(!demo)return;
    const stages=[()=>{setPanel('parameters');setWorld(w=>w?updateWorld(w,{carReduction:0}):w);},()=>setWorld(w=>w?updateWorld(w,{carReduction:100}):w),()=>setPanel('why'),()=>setWorld(w=>w?updateWorld(w,{transitInvestment:100}):w),()=>{setWorld(w=>w?createBranch(w,'Transit-first city'):w);setCompare(true);},()=>setPanel('model'),()=>setPanel('evidence'),()=>{onStopDemo();notify('The demo is complete. This reality is yours to explore.');}];
    let step=0;stages[0]();setDemoStep(0);
    const id=setInterval(()=>{step++;setDemoStep(step);stages[step]?.();if(step===stages.length-1)clearInterval(id);},5500);
    return()=>clearInterval(id);
  },[demo,setWorld,onStopDemo,notify]);
  function runCommand(){const parsed=interpretCommand(command,world.kind,definition);setCommand('');switch(parsed.type){case 'set':mutate(parsed.values);notify('Parameters updated locally.');break;case 'time':mutate(undefined,parsed.value);break;case 'branch':setBranchDialog(true);break;case 'compare':setCompare(true);break;case 'panel':setPanel(parsed.panel);break;case 'reset':mutate(Object.fromEntries(definition.variables.map(v=>[v.id,v.initial])),definition.time.initial);break;case 'focus':setFocus(parsed.nodeId??result.nodes[0]?.id??'');break;case 'unknown':notify(parsed.message);}}
  function branch(){try{setWorld(createBranch(world,branchName.trim()||undefined));setBranchDialog(false);setBranchName('');notify('Reality branched. Previous scenarios are preserved.');}catch(err){notify(err instanceof Error?err.message:'Could not create branch.');}}
  function reset(){mutate(Object.fromEntries(definition.variables.map(v=>[v.id,v.initial])),definition.time.initial);notify('Active scenario reset to model defaults.');}
  const whyNode=result.nodes.find(n=>n.id===selected);
  return <div className={'explorer '+(immersive?'explorer--immersive':'')}><div className="world-topbar"><div className="world-heading"><a href="#/library" aria-label="Back to world library"><ArrowLeft size={18}/></a><div><span className="eyebrow">{definition.category} / {definition.coordinates}</span><h1>{definition.title}</h1></div></div><div className="world-actions"><button className="secondary" onClick={()=>setBranchDialog(true)}><GitBranch size={16}/><span>Branch reality</span></button><button className={'secondary '+(compare?'selected':'')} aria-pressed={compare} onClick={()=>setCompare(!compare)}><Layers3 size={16}/><span>Compare</span></button><button className="icon-button" aria-label="Export world" onClick={()=>exportWorld(world)}><Download size={18}/></button><button className="icon-button" aria-label="Share world" onClick={onShare}><Share2 size={18}/></button></div></div>
    {demo&&<div className="demo-banner"><span><Play size={13}/>LIVING DEMO / {['Observe the baseline','Remove private cars','Trace the consequences','Expand transit','Branch a new reality','Look inside the model','Follow the evidence','Your turn'][demoStep]}</span><button onClick={onStopDemo}>Take control <X size={14}/></button></div>}
    <div className="workspace"><aside className="control-rail"><div className="rail-top"><span className="eyebrow">REALITY CONTROLS</span><button className="icon-button" onClick={reset} aria-label="Reset active scenario"><RotateCcw size={15}/></button></div><label className="branch-select"><GitBranch size={15}/><select aria-label="Active reality" value={world.activeBranchId} onChange={e=>{try{setWorld(switchBranch(world,e.target.value));}catch{notify('That branch could not be opened.');}}}>{world.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><ChevronDown size={14}/></label><p className="rail-intro">Change a variable.<br/>Follow what happens next.</p>{definition.variables.map(v=><div className="variable-control" key={v.id}><label htmlFor={v.id}>{v.label}<output>{format(world.parameters[v.id])}<span>{v.unit}</span></output></label><input type="range" id={v.id} min={v.min} max={v.max} step={v.step} value={world.parameters[v.id]} onChange={e=>{onStopDemo();mutate({[v.id]:Number(e.target.value)});}}/><div className="range-labels"><span>{v.min}{v.unit}</span><span>{v.max}{v.unit}</span></div><p>{v.description}</p></div>)}<div className="model-status"><span className="status-dot"/>DETERMINISTIC MODEL<p>{world.kind==='neural'?'Real local backpropagation. Fixed seed. Reproducible outputs.':world.kind==='system'?'Question-specific system map. Generic sensitivities are visible assumptions; public sources provide context only.':'Illustrative scenario. Outputs describe this model, not a real-world forecast.'}</p><button onClick={()=>setPanel('challenge')}>Explore the limits <ArrowUpRight size={13}/></button></div></aside>
    <section className="world-canvas-area" aria-label="Interactive world">{immersive&&whyNode&&<aside className="world-object-card" aria-label="Inspected place"><div><span className="eyebrow">LOOK CLOSER</span><button className="icon-button" aria-label="Close place details" onClick={()=>setSelected('')}><X size={16}/></button></div><h2>{whyNode.label}</h2><p>{whyNode.detail}</p><span className="fine-print">Illustrative environment · inspect the model and sources for its evidence.</span><button className="text-action" onClick={()=>{setImmersive(false);setPanel('why');}}>Inspect causes and evidence <ArrowUpRight size={15}/></button></aside>}<button className="immersive-toggle" aria-label={immersive?'Exit immersive world':'Expand immersive world'} aria-pressed={immersive} onClick={()=>setImmersive(value=>!value)}>{immersive?<Minimize2 size={16}/>:<Maximize2 size={16}/>}<span>{immersive?'Back to workspace':'Expand world'}</span></button><div className="scene-toolbar"><div className="segmented"><button className={!dataView&&panel!=='model'?'active':''} onClick={()=>{setDataView(false);setPanel('parameters');}}><Orbit size={14}/>World</button><button className={panel==='model'?'active':''} onClick={()=>{setDataView(false);setPanel('model');}}><ScanLine size={14}/>Model</button><button className={dataView?'active':''} onClick={()=>setDataView(true)}><Braces size={14}/>Data</button></div><span className="scene-badge">{world.kind==='neural'?'ACTUAL COMPUTATION':world.kind==='system'?'GENERATED EXPLORATORY MODEL':'HYPOTHETICAL SCENARIO'}</span></div>
    {!dataView?<Suspense fallback={sceneFallback}><WorldScene kind={world.kind} result={result} parameters={world.parameters} selectedId={selected} onSelect={id=>{setSelected(id);setPanel('why');}} focusId={focus} mode={panel==='model'?'model':'world'} blueprint={world.blueprint} reducedMotion={reduced}/></Suspense>:<div className="data-view"><p className="eyebrow">ACCESSIBLE WORLD DATA</p><h2>Every node, in plain sight.</h2><table><thead><tr><th>Entity</th><th>Value</th><th>Meaning</th></tr></thead><tbody>{result.nodes.map(n=><tr key={n.id}><th><button onClick={()=>{setSelected(n.id);setPanel('why');}}>{n.label}</button></th><td>{format(n.value)}</td><td>{n.detail}</td></tr>)}</tbody></table></div>}
    <div className="scene-caption"><span className="tiny-cross">+</span><span>{definition.subtitle}</span><button onClick={()=>{setFocus(result.nodes[0]?.id??'');notify('Camera focused on the first system node.');}}><LocateFixed size={15}/>Focus system</button></div>
    <div className="metrics-strip">{result.metrics.slice(0,4).map(m=><button className={selected===m.id?'active':''} key={m.id} onClick={()=>{setSelected(m.id);setPanel('why');}}><span>{m.label} <ArrowUpRight size={12}/></span><strong>{format(m.value)}<small>{m.unit}</small></strong><small className="metric-range">{world.kind==='neural'?'Computed value':'Modeled range'} {format(m.range[0])}–{format(m.range[1])}</small></button>)}</div>
    </section></div>
    <div className="timeline"><button className="icon-button play-control" onClick={()=>{onStopDemo();if(world.time>=definition.time.max)mutate(undefined,definition.time.min);setPlaying(!playing);}} aria-label={playing?'Pause timeline':'Play timeline'}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><div className="time-readout"><span className="eyebrow">{definition.time.label}</span><strong>{format(world.time)} <small>{definition.time.unit}</small></strong></div><div className="timeline-track"><input aria-label="Timeline" type="range" min={definition.time.min} max={definition.time.max} step={definition.time.step} value={world.time} onChange={e=>{setPlaying(false);mutate(undefined,Number(e.target.value));}}/><div className="time-events">{definition.time.events.map(e=><button key={e.at} onClick={()=>{setPlaying(false);mutate(undefined,e.at);}}>{e.label}</button>)}</div></div><span className="timeline-note">{world.kind==='neural'?'REPLAYABLE TRAINING':'SCENARIO TIME · NOT HISTORY'}</span></div>
    <section className="inspector"><div className="inspector-tabs" role="tablist" aria-label="Inspect world">{tabs.map(t=><button id={'tab-'+t.id} role="tab" aria-selected={panel===t.id} aria-controls="inspection-panel" key={t.id} onClick={()=>setPanel(t.id)}><t.icon size={15}/>{t.label}</button>)}</div><div id="inspection-panel" role="tabpanel" aria-labelledby={'tab-'+panel} className="inspection-content">
    {panel==='parameters'&&<div className="insight-intro"><div><p className="eyebrow">THIS WORLD IS AN OPEN QUESTION</p><h2>{world.question}</h2><p>{definition.description}</p></div><div className="insight-tip"><GitBranch/><h3>One change, many consequences.</h3><p>Select an outcome to trace its causes. Branch your reality before trying a different approach.</p></div></div>}
    {panel==='evidence'&&<><div className="section-heading"><div><p className="eyebrow">SOURCE DNA</p><h2>Know what you’re standing on.</h2></div><span className="mono">{definition.sources.length} SOURCES / {definition.claims.length} CLAIMS</span></div><div className="evidence-layout"><div className="claims">{[...definition.claims].sort((a,b)=>Number(pinned.includes(b.id))-Number(pinned.includes(a.id))).map(c=><article key={c.id} className="claim"><div className="claim-heading"><span className={'claim-type '+c.kind}>{c.kind}</span><button aria-label={(pinned.includes(c.id)?'Unpin ':'Pin ')+c.title} aria-pressed={pinned.includes(c.id)} onClick={()=>setPinned(p=>p.includes(c.id)?p.filter(x=>x!==c.id):[...p,c.id])}>{pinned.includes(c.id)?<Check size={14}/>:<Plus size={14}/>}</button></div><h3>{c.title}</h3><p>{c.detail}</p><p className="claim-limitation">{c.limitation}</p><div className="claim-footer"><span>{c.confidence} confidence</span>{c.sourceIds.map(id=><a key={id} href={'#source-'+id} onClick={e=>{e.preventDefault();document.getElementById('source-'+id)?.scrollIntoView({behavior:reduced?'instant':'smooth'});}}>[{id}]</a>)}</div></article>)}</div><div className="sources">{definition.sources.map(s=><article key={s.id} id={'source-'+s.id}><span className="eyebrow">{s.publisher}</span><h3><a href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={13}/></a></h3><p>{s.note}</p><small>Published: {s.published} · Reviewed: {s.accessed}</small></article>)}</div></div></>}
    {panel==='model'&&<><p className="eyebrow">X-RAY / EXECUTABLE STRUCTURE</p><h2>The mechanism beneath the world.</h2><div className="equations">{result.metrics.map(m=><article key={m.id}><h3>{m.label}</h3><code>{m.equation}</code><p>{m.explanation}</p><span className="mono">INPUTS / {m.inputs.join(' → ')}</span></article>)}</div><p className="fine-print">The spatial model view shows dependencies. Dashed links indicate uncertain assumptions; displayed equations document fixed code and are never evaluated from imported files.</p></>}
    {panel==='why'&&<><div className="section-heading"><div><p className="eyebrow">WHY / TRACE THE CAUSES</p><h2>{whyNode?whyNode.label:currentMetric?.label}</h2></div><select aria-label="Outcome to explain" value={currentMetric?.id??''} onChange={e=>setSelected(e.target.value)}>{result.metrics.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></div>{whyNode&&<p>{whyNode.detail}</p>}{currentMetric&&<Why metric={currentMetric} definition={definition} result={result}/>}</>}
    {panel==='challenge'&&<><div className="section-heading"><div><p className="eyebrow">CHALLENGE THIS WORLD</p><h2>A good model exposes its limits.</h2></div><button className="secondary" onClick={()=>{const extremes=Object.fromEntries(definition.variables.map((v,i)=>[v.id,i%2===0?v.max:v.min]));mutate(extremes);notify('Stress test applied to the active scenario. Inspect the results and model limits.');}}><AlertTriangle size={16}/>Break it</button></div><div className="challenge-list">{[...result.warnings,...definition.limitations].map((w,i)=><article key={i}><span>{(i+1).toString().padStart(2,'0')}</span><div><h3>{i<result.warnings.length?'Current scenario warning':'Model boundary'}</h3><p>{w}</p></div></article>)}</div><p className="fine-print">Challenge is a deterministic review of documented model boundaries and parameter conditions. It does not independently verify new research.</p></>}
    </div></section>
    {compare&&<section className="comparison"><div className="section-heading"><div><p className="eyebrow">BRANCH COMPARISON</p><h2>See the difference a decision makes.</h2></div><button className="icon-button" aria-label="Close comparison" onClick={()=>setCompare(false)}><X size={18}/></button></div><div className="comparison-scroll"><table><thead><tr><th>Outcome</th><th>{baseline.name}<small>{baseline.time} {definition.time.unit}</small></th><th>{active?.name??'Current reality'}<small>{world.time} {definition.time.unit}</small></th><th>Difference</th></tr></thead><tbody>{result.metrics.map(m=>{const b=baselineResult.metrics.find(b=>b.id===m.id)?.value??0;const delta=m.value-b;return <tr key={m.id}><th>{m.label}</th><td>{format(b)} {m.unit}</td><td>{format(m.value)} {m.unit}</td><td className={delta===0?'':(m.good==='up'?delta>0:m.good==='down'?delta<0:false)?'accent':'amber'}>{delta>0?'+':''}{format(delta)} {m.unit}</td></tr>;})}</tbody></table></div><p className="fine-print">Differences compare model outputs at the displayed times. Ranges are sensitivity envelopes, not statistical confidence intervals.</p></section>}
    <div className="command-bar"><CommandIcon size={17}/><form onSubmit={e=>{e.preventDefault();runCommand();}}><label htmlFor="command" className="sr-only">Command this world</label><input id="command" value={command} onChange={e=>setCommand(e.target.value)} maxLength={500} placeholder={world.kind==='manhattan'?'Try “remove private cars” or “compare with baseline”':'Try “branch this reality” or “challenge this model”'}/><button type="submit" aria-label="Run command"><ArrowRight size={17}/></button></form><span className="save-status"><span className="status-dot"/>{saveStatus}</span></div>
    {branchDialog&&<Modal title="BRANCH REALITY" onClose={()=>setBranchDialog(false)}><h2>Give this possibility a name.</h2><p>Freeze the current parameters and time in a new, independent scenario.</p><form onSubmit={e=>{e.preventDefault();branch();}}><label htmlFor="branch-name">Reality name</label><input className="text-input" id="branch-name" value={branchName} maxLength={70} onChange={e=>setBranchName(e.target.value)} placeholder="A different possibility" autoFocus/><button type="submit" className="primary">Create branch <GitBranch size={16}/></button></form></Modal>}
  </div>;
}

function Why({metric,definition,result}:{metric:Metric;definition:WorldDefinition;result:SimulationResult}){return <div className="why-layout"><div className="why-value"><strong>{format(metric.value)}<span>{metric.unit}</span></strong><p>{metric.explanation}</p><code>{metric.equation}</code></div><div className="causal-trace">{metric.inputs.map((input,i)=>{const v=definition.variables.find(v=>v.id===input);const n=result.nodes.find(n=>n.id===input);return <div className="trace-step" key={input}><span className="trace-number">{i+1}</span><div><h3>{v?.label??n?.label??input}</h3><p>{v?.description??n?.detail??'Intermediate value computed by the simulation.'}</p></div><ArrowRight size={16}/></div>;})}<div className="trace-result"><BookOpen size={16}/><span>{metric.claimIds.length} linked claims · inspect Source DNA for evidence and assumptions.</span></div></div></div>;}
